### ISSUE TITLE
[FEATURE] 내부 POD간 커뮤니케이션 인터페이스

### ISSUE THREAD

**Issue by imxsuu** [keti-openfx/openfx#1]
## 🚀 Feature

- 내부 POD간 커뮤니케이션이 가능한 인터페이스를 구축

## Motivation

- 현재의 OpenFx 플랫폼을 사용할 사용자는 단일 함수 호출만이 가능
- FaaS를 제공하는 플랫폼으로써 함수 간 커뮤니케이션은 필수로 제공되어야함
- 내부 POD간 커뮤니케이션이 가능한 인터페이스를 구축하여 사용자가 한 번의 호출로 다수의 함수에 접근할 수 있도록 한다.

## Pitch

- 단일 함수만 호출 가능

## Alternatives

- 내부 POD간 커뮤니케이션이 가능한 인터페이스를 구축하여 사용자가 한 번의 호출로 다수의 함수에 접근 가능

**Comment by ssaru** [comment]
사무실에 가셔서, 해당 Feature Part만 새로 OpenFx 서버 설치해서 모든 기능이 작동하는지 테스트 하신 후에 Pull Request 날려주세요~
